home: Domů
categories: Kategorie
search: Hledat
tags: Tagy
tweets: Tweety
prev: Předchozí
next: Další
comment: Komentáře
archives: Archív
page: Stránka
recent_posts: Nedávné
close: Zavřít
posts_list: Příspěvky
about: O nás
rss: rss
main_site: Hlavní stránka
read_more: Více
